export const carfilterData = [
  {
    key: "brands",
    name: "Car Brand",
    type: "checkbox",
    values: [
      { label: "Tesla", value: "Tesla" },
      { label: "Ford", value: "Ford" },
      { label: "Mercedes Benz", value: "Mercedes Benz" },
      { label: "Audi", value: "Audi" },
      { label: "Kia", value: "Kia" },
      { label: "Honda", value: "Honda" },
      { label: "Toyota", value: "Toyota" },
    ],
  },
  {
    key: "category",
    name: "Car Category",
    type: "checkbox",
    values: [
      { label: "Convertible (25)", value: "Convertible" },
      { label: "Coupe (15)", value: "Coupe" },
      { label: "Sedan (10)", value: "Sedan" },
      { label: "EV (5)", value: "EV" },
      { label: "Hatchback (123)", value: "Hatchback" },
      { label: "Luxury (06)", value: "Luxury" },
      { label: "SUV (6)", value: "SUV" },
      { label: "Wagon (5)", value: "Wagon" },
    ],
  },
  {
    key: "years",
    name: "Year",
    type: "checkbox",
    values: [
      { label: "2024", value: 2024 },
      { label: "2022", value: 2022 },
      { label: "2021", value: 2021 },
      { label: "2020", value: 2020 },
      { label: "2019", value: 2019 },
      { label: "2018", value: 2018 },
    ],
  },
  {
    key: "fuelType",
    name: "Fuel Type",
    type: "radio",
    values: [
      { label: "Petrol", value: "Petrol" },
      { label: "Diesel", value: "Diesel" },
      { label: "Electric", value: "Electric" },
      { label: "CNG", value: "CNG" },
    ],
  },
  {
    key: "specifications",
    name: "Car Specifications",
    type: "checkbox",
    values: [
      { label: "Air Conditioners", value: "AC" },
      { label: "Keyless", value: "Keyless" },
      { label: "Panoramic", value: "Panoramic" },
      { label: "Bluetooth", value: "Bluetooth" },
      { label: "Aux", value: "Aux" },
      { label: "Top Window", value: "Top Window" },
      { label: "Speakers", value: "Speakers" },
      { label: "Automatic Window", value: "Automatic Window" },
    ],
  },
  {
    key: "seating",
    name: "Capacity",
    type: "checkbox",
    values: [
      { label: "2 Seater", value: 2 },
      { label: "4 Seater", value: 4 },
      { label: "5 Seater", value: 5 },
      { label: "7 Seater", value: 7 },
    ],
  },
  {
    key: "transmission",
    name: "Transmission",
    type: "radio",
    values: [
      { label: "Manual", value: "Manual" },
      { label: "Semi Automatic", value: "Semi Automatic" },
      { label: "Automatic", value: "Automatic" },
    ],
  },
];